### ISSUE TITLE
Not found "Crypto" module named

### ISSUE THREAD

**Issue by AlbertDer** [can-kat/cstealer#24]
![image](https://user-images.githubusercontent.com/68430489/230648462-31b504ef-a9e8-44c0-ba9c-373dbeac6d45.png)

Eventually I have already installed the crypto module and its extensions and everything related to it but still when I run the .exe I get this damn message, please fix it now or tell me what I'm doing wrong

**Comment by can-kat** [comment]
It seems like you are trying to import the Crypto module in your Python code, but the module is not found.

The Crypto module is not a built-in Python module and needs to be installed separately. You can install it using the following command in your terminal or command prompt:

`pip install pycrypto`

Alternatively, you can also use the pycryptodome module, which is a drop-in replacement for the Crypto module and provides additional features and security improvements. You can install it using the following command:

`pip install pycryptodome`

Once you have installed the module, If you're still getting that error it may cause of case sensitivity of `crypto` folder.
Just change the name of the folder:

`C:\Python311\Lib\site-packages\crypto`

To this:

`C:\Python311\Lib\site-packages\Crypto`
