### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by RiaxStuff** [can-kat/cstealer#28]
Hello @can-kat , I cannot build the stub for whatever reason. No error output or anything.

I downloaded the req without any issues but when I try to build it I had no success.
It just replied with build was successful but there is no stub or anything and it has nothing to do with antivirus

**Comment by rice7th** [comment]
Did you run it after building?

A build without warning nor errors is a successful build..

**Comment by RiaxStuff** [comment]
what do u mean? It didn't generate the .exe

**Comment by can-kat** [comment]
Hi there,

Please double check required libs are installed and It should create a folder called `dist` after build. If that folder didn't created please reinstall Python and all required libs again.

**Comment by yo69hh** [comment]
where do i get the webhok from or just build
