### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by DennisMihaltan** [can-kat/cstealer#33]
I complete all the steps, and start "start.bat"... when I put the Discord webhook, appear this error: 

Traceback (most recent call last):
  File "C:\Users\...\cstealer-main\cstealer-main\builder.py", line 64, in <module>
    with open(filepath, "r", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\...\\cstealer-main\\cstealer-main\\main.py'

What can I do?

**Comment by can-kat** [comment]
Dear DennisMihalt,

Thank you for bringing this issue to my attention. I apologize for the inconvenience you are facing with the "start.bat" script. The error you encountered seems to be related to the absence of the `main.py` file in the specified directory.

To help you resolve this issue, please follow these potential steps:

1. Double-check the File Path:
`Ensure that the file path provided in the "start.bat" script is correct and points to the correct location of the "main.py" file. It's possible that there might be a typo or a mistake in the path, leading to the "FileNotFoundError."`

2. Verify the File Existence:
`Manually verify if the "main.py" file exists in the specified directory. If it does not, please make sure you have the correct file in the right location. If the file is missing, you might need to obtain it from the repository or other sources.`

3. Update the Path:
`If the "main.py" file is in a different directory, update the file path in the "builder.py" script (line 64) to reflect the correct location of the "main.py" file.`

4. File Permissions:
`Ensure that you have sufficient permissions to access the files in the specified directory. If necessary, grant the required permissions to the directory and files.`

5. Check Dependencies:
`Verify that all necessary dependencies and libraries are correctly installed. It's possible that the script requires specific dependencies to function correctly.`

6. Repository Structure:
`Check the repository's structure to ensure it contains all the necessary files and directories required to run the "start.bat" script.`

Once you have tried these steps, please run the `start.bat` script again. If the issue persists, please let me know and provide any additional details or error messages you encounter. This information will be invaluable for further investigation, and I'll do my best to assist you in resolving the problem.

**Comment by DennisMihaltan** [comment]
Thank you so much... I think it was the 2 problem
