### ISSUE TITLE
WHERE IS DIST FOLDER

### ISSUE THREAD

**Issue by R2ew** [can-kat/cstealer#38]

**Comment by R2ew** [comment]
well i enter the webhook, press build EXE and nothing happens

**Comment by can-kat** [comment]
Please change the file extension to `builder.pyw > builder.py` and run the file again to see the error.

**Comment by CEOofKohler** [comment]
Had the same issue here, the console said:

 'pyinstaller' is not recognized as an internal or external command,
operable program or batch file.

I did 2 things to fix the issue (not sure which actually helped).
1. Changed from a Microsoft account to a local user account
2. Turned off python in "App Execution Aliases"

**Comment by KARMAzm** [comment]
can you explain what is the Changed from a Microsoft account to a local user account

**Comment by KARMAzm** [comment]
i have same problem
