### ISSUE TITLE
files wont upload

### ISSUE THREAD

**Issue by fxtazz** [can-kat/cstealer#39]
Well, some files get uploaded, and others don't.

![image](https://github.com/can-kat/cstealer/assets/170032672/fa7b2acd-6c09-4aba-b762-743b641df1fc)

![image](https://github.com/can-kat/cstealer/assets/170032672/a51562e3-f760-4358-a7a7-a65f9f6fd0d9)

**Comment by can-kat** [comment]
Hi, this situation may occur due to the GoFile API's limitations.
