### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Meliodas183** [can-kat/cstealer#40]
Someone installed this on my pc (the compiled file) and i would like to know if there is a way to remove it without reinstalling windows? If you could contact me on discord: ii_meliodas_ii

**Comment by profumato4** [comment]
use malwarebytes to scan your pc it will reveal the .exe file and remove it

**Comment by JosePraveenK** [comment]
I did do my scan but I can't find the exe but, I have manually uninstalled it. from the startup. today I tried to change my Discord password. I got my password in my Discord webhook. if that's the case how to remove the discord injector

**Comment by h9nt** [comment]
> Someone installed this on my pc (the compiled file) and i would like to know if there is a way to remove it without reinstalling windows? If you could contact me on discord: ii_meliodas_ii

So why u install random files before Checkout what is do, even reverse engineering, if u know how

**Comment by can-kat** [comment]
Hello, I highly recommend changing all passwords and formatting your PC.
