### ISSUE TITLE
install.batch issue

### ISSUE THREAD

**Issue by Dgos4** [can-kat/cstealer#49]
pip' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .

well, it is not working. this pops up when i open install.batch please help me

**Comment by profumato4** [comment]
u need to install python ig

**Comment by can-kat** [comment]
Hello,

While installing Python click 'Add to PATH' checkbox and try again.

**Comment by HamzaNegs** [comment]
> Hello,
> 
> While installing Python click 'Add to PATH' checkbox and try again.

Where am I supposed to go to add to path? when i download python it just shows moderate, repair and uninstall.
