### ISSUE TITLE
Additional functionality?

### ISSUE THREAD

**Issue by GEkXD3** [can-kat/cstealer#59]
Hello! I have 2 questions

1. Is CStealer can turn on PC by itself?
2. How victim can delete this stealer from the PC? Is scanning with Microsoft Defender will help? Can victim just delete the executable and CStealer will not remain on the computer?

**Comment by can-kat** [comment]
Hello,

1. CStealer cannot turn on PC.
2. I recommend resetting the computer to make sure.
