### ISSUE TITLE
May Lead to Account Suspension

### ISSUE THREAD

**Issue by MikoGetBread** [can-kat/cstealer#67]
If you are considering or currently using this software for personal or academic research, be aware that even when used solely on your own devices and for legitimate purposes, it may lead to a suspension of your Discord account.

Recently, I conducted a personal project involving this software to analyze its behavior in a controlled environment on my personal computer. Despite following ethical guidelines and using the software for academic research only, my Discord account was suspended due to what appears to be a misunderstanding related to Discord's policies on Malicious Conduct.

If you choose to proceed with using this software despite this warning, consider creating a new Discord account specifically for testing. This approach can help avoid any potential impact on your primary account. Alternatively, you may want to wait for updates or patches to address these issues before using the software to ensure compliance with platform policies and to avoid unnecessary complications.

![ss](https://github.com/user-attachments/assets/002fd24b-0dd8-497a-82bb-0521be749735)

**Comment by can-kat** [comment]
Hello,
Thank you for informing. I have pinned this issue.

**Comment by Burnedfart** [comment]
This happened to my account too a while back, have you had any luck getting it back?

**Comment by MikoGetBread** [comment]
> This happened to my account too a while back, have you had any luck getting it back?

my situation I was suspended for 2 years for the first server, and the second server caused permanent suspension (i used two servers). I emailed back and forth but they weren't interested and gave only vague replies. you can login to your account and it should say your account status


![image](https://github.com/user-attachments/assets/3c35b1f9-d943-43b1-9bde-94fed23c4707)

**Comment by Burnedfart** [comment]
yeah what's confusing for me is I only used it on one server. it says im permanently suspended but at the same time says the violation only lasts until june of 2026 so i'm confused about if it's gone for 2 years or forever. support wasnt helpful at all

**Comment by 20laid** [comment]
> > This happened to my account too a while back, have you had any luck getting it back?
> 
> my situation I was suspended for 2 years for the first server, and the second server caused permanent suspension (i used two servers). I emailed back and forth but they weren't interested and gave only vague replies. you can login to your account and it should say your account status
> 
> ![image](https://private-user-images.githubusercontent.com/172203188/364954555-3a087f93-8383-4c8a-bc4c-1c900fd8ab2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMTI5MDMsIm5iZiI6MTcyNzExMjYwMywicGF0aCI6Ii8xNzIyMDMxODgvMzY0OTU0NTU1LTNhMDg3ZjkzLTgzODMtNGM4YS1iYzRjLTFjOTAwZmQ4YWIyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QxNzMwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDhjNzNhNWYyZGU1ZmQwYjZlMWRhYmFkMGZhN2Q4OTQyZjI1ZTlhYTljMTk0ZjI1OTY2NDA1MmE2Yzc0NDQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ALvk4r_MKPRpgkYERyGuVy6SxzULxHBRrbfwbfu-nFw)

hey how long was your server/account up for until you got banned by discord

**Comment by Burnedfart** [comment]
> hey how long was your server/account up for until you got banned by discord
 
i think 1-2 weeks? i noticed the server was deleted (by discord) and then about a week later my account was banned
