### ISSUE TITLE
Question about: VM

### ISSUE THREAD

**Issue by Techyh** [can-kat/cstealer#79]
### Hello,

I've encountered a problem:
After i did the setup and runned the new virus file on my VM, i didn't get any message from the webhook on discord.
My questions are:

**Are all VM's blocked?**

**Is it normal that i didn't get any message by the webhook?**

**Comment by Hilly1515** [comment]
i think it detects both virtualbox and vmware when i tried it

**Comment by sdas1247** [comment]
its a sacm dont run anything factory reset your pc right now , he stole my 365$ from my crypto wallet.

**Comment by can-kat** [comment]
Hello,

Yes, it has anti-vm feature inside of the code.
