### ISSUE TITLE
Windows AV picks this up

### ISSUE THREAD

**Issue by SuppliedOrange** [can-kat/cstealer#83]
I cannot install this on my Chromium, because Windows AV picks it up as a Trojan 

![image](https://github.com/user-attachments/assets/4b37f507-602b-42ba-b659-bca14d86c527)
![image](https://github.com/user-attachments/assets/265410c7-28ae-4ab9-aafa-0107df771102)

**Comment by Hilly1515** [comment]
its for educational purposes (even tho its dual hooked) so u know it will always be detected

**Comment by SuppliedOrange** [comment]
Really? I knew he was using remote code but I didn't find anything particularly suspicious.
https://raw.githubusercontent.com/wtfcstealerwtf/index/main/injection.js

I think the reason you saw that they're being logged in is because the remote script actually attempts to log in.

**Comment by SuppliedOrange** [comment]
@can-kat why are you being deleting comments? Are you hiding something?

**Comment by can-kat** [comment]
I cannot hide anything, EVERYTHING IS OPEN-SOURCE WITHOUT ANY OBFUSCATION. People spreading false information that makes me so angry.
